*$OSCAR_WILDE_QUOTES = %(A cynic is a man who knows the price of everything but the value of nothing.),
%(A little sincerity is a dangerous thing, and a great deal of it is absolutely fatal.),
%(A man can't be too careful in the choice of his enemies.),
%(A man's face is his autobiography. A woman's face is her work of fiction.),
%(A poet can survive everything but a misprint.),
%(A thing is not necessarily true because a man dies for it.),
%(A true friend stabs you in the front.),
%(A work of art is the unique result of a unique temperament.),
%(Ah, well, then I suppose I shall have to die beyond my means.),
%(Alas, I am dying beyond my means.),
%(All art is quite useless.),
%(All bad poetry springs from genuine feeling.),
%(All that I desire to point out is the general principle that life imitates art far more than art imitates life.),
%(All women become like their mothers. That is their tragedy. No man does. That's his.),
%(Always forgive your enemies - nothing annoys them so much.),
%(Ambition is the germ from which all growth of nobleness proceeds.),
%(Ambition is the last refuge of the failure.),
%(America is the only country that went from barbarism to decadence without civilization in between.),
%(An idea that is not dangerous is unworthy of being called an idea at all.),
%(Arguments are extremely vulgar, for everyone in good society holds exactly the same opinion.),
%(Arguments are to be avoided: they are always vulgar and often convincing.),
%(Art is the most intense mode of individualism that the world has known.),
%(As long as a woman can look ten years younger than her own daughter, she is perfectly satisfied.),
%(As long as war is regarded as wicked, it will always have its fascination. When it is looked upon as vulgar, it will cease to be popular.),
%(As yet, Bernard Shaw hasn't become prominent enough to have any enemies, but none of his friends like him.),
%(At 46 one must be a miser; only have time for essentials.),
%(Between men and women there is no friendship possible. There is passion, enmity, worship, love, but no friendship.),
%(Bigamy is having one wife too many. Monogamy is the same.),
%(Biography lends to death a new terror.),
%(By giving us the opinions of the uneducated, journalism keeps us in touch with the ignorance of the community.),
%(Charity creates a multitude of sins.),
%(Children begin by loving their parents; after a time they judge them; rarely, if ever, do they forgive them.),
%(Conscience and cowardice are really the same things. Conscience is the trade-name of the firm. That is all.),
%(Consistency is the last refuge of the unimaginative.),
%(Consistency is the last resort of the unimaginative.),
%(Conversation about the weather is the last refuge of the unimaginative.),
%(Deceiving others. That is what the world calls a romance.),
%(Democracy means simply the bludgeoning of the people by the people for the people.),
%(Do you really think it is weakness that yields to temptation? I tell you that there are terrible temptations which it requires strength, strength and courage to yield to.),
%(Education is an admirable thing, but it is well to remember from time to time that nothing that is worth knowing can be taught.),
%(Every portrait that is painted with feeling is a portrait of the artist, not of the sitter.),
%(Every saint has a past and every sinner has a future.),
%(Everything popular is wrong.),
%(Experience is one thing you can't get for nothing.),
%(Experience is simply the name we give our mistakes.),
%(Fashion is a form of ugliness so intolerable that we have to alter it every six months.),
%(Fathers should be neither seen nor heard. That is the only proper basis for family life.),
%(Hatred is blind, as well as love.),
%(He has no enemies, but is intensely disliked by his friends.),
%(He lives the poetry that he cannot write. The others write the poetry that they dare not realise.),
%(He must have a truly romantic nature, for he weeps when there is nothing at all to weep about.),
%(He was always late on principle, his principle being that punctuality is the thief of time.),
%(How can a woman be expected to be happy with a man who insists on treating her as if she were a perfectly normal human being.),
%(How marriage ruins a man! It is as demoralizing as cigarettes, and far more expensive.),
%(I always pass on good advice. It is the only thing to do with it. It is never of any use to oneself.),
%(I am not young enough to know everything.),
%(I can resist everything except temptation.),
%(I dislike arguments of any kind. They are always vulgar, and often convincing.),
%(I have nothing to declare except my genuis.),
%(I have the simplest tastes. I am always satisfied with the best.),
%(I hope you have not been leading a double life, pretending to be wicked and being really good all the time. That would be hypocrisy.),
%(I never travel without my diary. One should always have something sensational to read in the train.),
%(I put all my genius into my life; I put only my talent into my works.),
%(I regard the theatre as the greatest of all art forms, the most immediate way in which a human being can share with another the sense of what it is to be a human being.),
%(I see when men love women. They give them but a little of their lives. But women when they love give everything.),
%(I sometimes think that God in creating man somewhat overestimated his ability.),
%(I suppose society is wonderfully delightful. To be in it is merely a bore. But to be out of it is simply a tragedy.),
%(I think that God, in creating man, somewhat overestimated his ability.),
%(I want my food dead. Not sick, not dying, dead.),
%(If one cannot enjoy reading a book over and over again, there is no use in reading it at all.),
%(If one could only teach the English how to talk, and the Irish how to listen, society here would be quite civilized.),
%(If one plays good music, people don't listen and if one plays bad music people don't talk.),
%(If there was less sympathy in the world, there would be less trouble in the world.),
%(If you are not too long, I will wait here for you all my life.),
%(If you pretend to be good, the world takes you very seriously. If you pretend to be bad, it doesn't. Such is the astounding stupidity of optimism.),
%(Illusion is the first of all pleasures.),
%(In all matters of opinion, our adversaries are insane.),
%(In America the President reigns for four years, and Journalism governs forever and ever.),
%(In America the young are always ready to give to those who are older than themselves the full benefits of their inexperience.),
%(In England people actually try to be brilliant at breakfast. That is so dreadful of them! Only dull people are brilliant at breakfast.),
%(In every first novel the hero is the author as Christ or Faust.),
%(In married life three is company and two none.),
%(It is a very sad thing that nowadays there is so little useless information.),
%(It is absurd to divide people into good and bad. People are either charming or tedious.),
%(It is an odd thing, but every one who disappears is said to be seen at San Francisco. It must be a delightful city, and possess all the attractions of the next world.),
%(It is better to be beautiful than to be good. But... it is better to be good than to be ugly.),
%(It is better to have a permanent income than to be fascinating.),
%(It is only an auctioneer who can equally and impartially admire all schools of art.),
%(It is perfectly monstrous the way people go about, nowadays, saying things against one behind one's back that are absolutely and entirely true.),
%(It is through art, and through art only, that we can realise our perfection.),
%(It is what you read when you don't have to that determines what you will be when you can't help it.),
%(Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.),
%(Laughter is not at all a bad beginning for a friendship, and it is far the best ending for one.),
%(Life imitates art far more than art imitates Life.),
%(Life is far too important a thing ever to talk seriously about.),
%(Life is never fair, and perhaps it is a good thing for most of us that it is not.),
%(Life is too important to be taken seriously.),
%(Man is a rational animal who always loses his temper when he is called upon to act in accordance with the dictates of reason.),
%(Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth.),
%(Memory... is the diary that we all carry about with us.),
%(Men always want to be a woman's first love - women like to be a man's last romance.),
%(Moderation is a fatal thing. Nothing succeeds like excess.),
%(Morality is simply the attitude we adopt towards people whom we personally dislike.),
%(Most modern calendars mar the sweet simplicity of our lives by reminding us that each day that passes is the anniversary of some perfectly uninteresting event.),
%(Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.),
%(Most people die of a sort of creeping common sense, and discover when it is too late that the only things one never regrets are one's mistakes.),
%(Mrs. Allonby: No man does. That is his.),
%(Music is the art which is most nigh to tears and memory.),
%(Music makes one feel so romantic - at least it always gets on one's nerves - which is the same thing nowadays.),
%(My great mistake, the fault for which I can't forgive myself, is that one day I ceased my obstinate pursuit of my own individuality.),
%(No great artist ever sees things as they really are. If he did, he would cease to be an artist.),
%(No man is rich enough to buy back his past.),
%(No object is so beautiful that, under certain conditions, it will not look ugly.),
%(No woman should ever be quite accurate about her age. It looks so calculating.),
%(Nothing can cure the soul but the senses, just as nothing can cure the senses but the soul.),
%(Nothing is so aggravating than calmness.),
%(Nothing makes one so vain as being told one is a sinner. Conscience makes egotists of us all.),
%(Now that the House of Commons is trying to become useful, it does a great deal of harm.),
%(Nowadays to be intelligible is to be found out.),
%(Of course America had often been discovered before Columbus, but it had always been hushed up.),
%(Of course I have played outdoor games. I once played dominoes in an open air cafe in Paris.),
%(One can survive everything, nowadays, except death, and live down everything except a good reputation.),
%(One of the many lessons that one learns in prison is, that things are what they are and will be what they will be.),
%(One should always be in love. That is the reason one should never marry.),
%(One should always play fairly when one has the winning cards.),
%(One's past is what one is. It is the only way by which people should be judged.),
%(Only the shallow know themselves.),
%(Ordinary riches can be stolen; real riches cannot. In your soul are infinitely precious things that cannot be taken from you.),
%(Our ambition should be to rule ourselves, the true kingdom for each one of us; and true progress is to know more, and be more, and to do more.),
%(Patriotism is the virtue of the vicious.),
%(Perhaps, after all, America never has been discovered. I myself would say that it had merely been detected.),
%(Pessimist: One who, when he has the choice of two evils, chooses both.),
%(Please do not shoot the pianist. He is doing his best.),
%(Questions are never indiscreet, answers sometimes are.),
%(Self-denial is the shining sore on the leprous body of Christianity.),
%(Selfishness is not living as one wishes to live, it is asking others to live as one wishes to live.),
%(Seriousness is the only refuge of the shallow.),
%(She wore far too much rouge last night and not quite enough clothes. That is always a sign of despair in a woman.),
%(Some cause happiness wherever they go; others whenever they go.),
%(Some of these people need ten years of therapy -ten sentences of mine do not equal ten years of therapy.),
%(Success is a science; if you have the conditions, you get the result.),
%(The basis of optimism is sheer terror.),
%(The books that the world calls immoral are books that show the world its own shame.),
%(The cynic knows the price of everything and the value of nothing.),
%(The difference between literature and journalism is that journalism is unreadable and literature is not read.),
%(The English country gentleman galloping after a fox - The unspeakable in full pursuit of the uneatable.),
%(The General was essentially a man of peace, except of course in his domestic affairs.),
%(The good ended happily, and the bad unhappily. That is what fiction means.),
%(The imagination imitates. It is the critical spirit that creates.),
%(The man who can dominate a London dinner-table can dominate the world.),
%(The moment you think you understand a great work of art, it's dead for you.),
%(The old believe everything, the middle-aged suspect everything, the young know everything.),
%(The one charm about marriage is that it makes a life of deception absolutely necessary for both parties.),
%(The only thing to do with good advice is to pass it on. It is never of any use to oneself.),
%(The only way to get rid of temptation is to yield to it... I can resist everything but temptation.),
%(The public is wonderfully tolerant. It forgives everything except genius.),
%(The pure and simple truth is rarely pure and never simple.),
%(The salesman knows nothing of what he is selling save that he is charging a great deal too much for it.),
%(The true mystery of the world is the visible, not the invisible.),
%(The truth is rarely pure and never simple.),
%(The typewriting machine, when played with expression, is no more annoying than the piano when played by a sister or near relation.),
%(The world has grown suspicious of anything that looks like a happily married life.),
%(The world is divided into two classes, those who believe the incredible, and those who do the improbable.),
%(There are only two kinds of people who are really fascinating - people who know absolutely everything, and people who know absolutely nothing.),
%(There are only two tragedies in life: one is not getting what one wants, and the other is getting it.),
%(There is no sin except stupidity.),
%(There is no such thing as a moral or an immoral book. Books are well written, or badly written.),
%(There is no such thing as an omen. Destiny does not send us heralds. She is too wise or too cruel for that.),
%(There is nothing in the world like the devotion of a married woman. It is a thing no married man knows anything about.),
%(There is nothing so difficult to marry as a large nose.),
%(There is only one thing in life worse than being talked about, and that is not being talked about.),
%(These days man knows the price of everything, but the value of nothing.),
%(This suspense is terrible. I hope it will last.),
%(Those whom the gods love grow young.),
%(To expect the unexpected shows a thoroughly modern intellect.),
%(To lose one parent may be regarded as a misfortune; to lose both looks like carelessness.),
%(To love oneself is the beginning of a lifelong romance.),
%(True friends stab you in the front.),
%(We are all in the gutter, but some of us are looking at the stars.),
%(What we have to do, what at any rate it is our duty to do, is to revive the old art of Lying.),
%(When a man has once loved a woman he will do anything for her except continue to love her.),
%(When good Americans die they go to Paris.),
%(When I was young I thought that money was the most important thing in life; now that I am old I know that it is.),
%(When the gods wish to punish us they answer our prayers.),
%(Whenever people agree with me I always feel I must be wrong.),
%(Who, being loved, is poor?),
%(Why was I born with such contemporaries?),
%(Woman begins by resisting a man's advances and ends by blocking his retreat.),
%(Women are made to be loved, not understood.),
%(Women are never disarmed by compliments. Men always are. That is the difference between the sexes.),
%(Work is the curse of the drinking classes.)

# Returns a random Oscar Wilde quote from a collection of 191 different snippets
# from his many works.
def oscar_wilde_quote
  $OSCAR_WILDE_QUOTES[rand($OSCAR_WILDE_QUOTES.length)]
end