enabled: false
host: 127.0.0.1
port: 9050

deny: all
allow:
 - 127.0.0.1
 - 192.168.1.*

# Set your access control permissions above.
# Values for deny and allow can be several
# things:
#
#  * The 'all' keyword can be used to match
#    everything.
#  * A single IP can be given right after
#    the colon.
#  * A single IP with wildcards can be given
#  * Or, combining all of these, a YAML list
#    can be used to specify many policies.
#    See the comments below for more examples.
#
# Also note, the "host" field above may also
# affect the ability for DRb clients to connect
# to the server. If you wish you receive
# connections from the 192.168.1.*, listen on
# the IP associated with this machine on that
# subnet.
#
#
# USING YAML LISTS
#
# YAML allows lists of items to be created by
# prepending a hyphen to each list element.
# These lists can be used to refine your
# access control list better. Example:
#
# deny: all
# allow:
#   - 192.168.1.123
#   - 192.168.1.99
#   - 66.199.34.44

